### ISSUE TITLE
Add support for OpenShift 4.0

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-openshift#139]
ManageIQ uses `/oapi/Foo` endpoints for all openshift-specific resources.
This was an openshift-specific path, probably predating api groups in k8s; all these have long been mirrored as various "normal" api groups e.g. `/apis/template.openshift.io/Template`.

IIUC, https://github.com/openshift/origin/pull/21782 completely dropped /oapi from Openshift 4.0.
Good riddance, but that means **ManageIQ will not work against Openshift 4.0**.

cc @oourfali @jhernand @agrare for visibility.

**Comment by cben** [comment]
Not sure yet how much "will not work".  Ideally k8s parts should still work, but I don't remember how tolerant the inventory code is to partial failures.  Will update when I get around to testing this.

**Comment by agrare** [comment]
Hey @cben thanks a lost for the ping!

It it as simple as switching from `/oapi` to `/apis/user.openshift.io`?  Is that newer api available on older openshift versions as well, or is it a hard `if >= 4.0; /apis/user.openshift.io; else /oapi; end`

**Comment by cben** [comment]
@ourfali tells me we don't intend to support openshift 4.x at all.

> It it as simple as switching from /oapi to /apis/user.openshift.io?

A little bit harder, as there are multiple api groups under /apis, and we'll need a separate `Kubeclient::Client` for each group.

> Is that newer api available on older openshift versions as well

Yes, starting 3.6.  Do we support anything older?

> `if >= 4.0`

Due to https://github.com/openshift/origin/issues/22901, version-sniffing 4.x is problematic.  
But presence of old / new endpoints is not hard to test.

**Comment by cben** [comment]
@agrare Does https://github.com/ManageIQ/manageiq-providers-openshift/blob/master/app/models/manageiq/providers/openshift/container_manager/container_template.rb also need adaptation?
It already does `api_group => "template.openshift.io"` to process the template itself, but not sure about `create_object`...  I _think_ it takes apiVersion and kind from the template itself, so maybe it does work? (assuming the template is openshift 4 compatible)

Also `create_project` https://github.com/ManageIQ/manageiq-providers-openshift/blob/29370d2b65aa8162d2b297a55b41568876407738/app/models/manageiq/providers/openshift/container_manager.rb#L39-L40

I no longer remember what user-visible functionalities these supports :-|

It might make sense to lift some of the #164 changes into container_manager_mixin.rb, your call.

---
As you notice, I'm increasingly losing touch with manageiq, had near zero work time for it last few months...  The time I do have I prefer to focus on kubeclient.

**Comment by agrare** [comment]
Thanks @cben I missed create_project (I was searching for `\.connect`)

I thought that connect_client handled that by doing `api, version = api_version.split('/', 2)` and `:path => '/apis/' + api` but I'll double check
