### ISSUE TITLE
Add dependency on manageiq-providers-kubernetes

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-providers-openshift#14]
Based on:
```
app/models/manageiq/providers/openshift/container_manager/refresher.rb:15:        hawk = ManageIQ::Providers::Kubernetes::ContainerManager::MetricsCapture::HawkularClient.new(ems, '_ops')
```
I think `manageiq-providers-openshift` should depend on `manageiq-providers-kubernetes`

**Comment by simon3z** [comment]
@zakiva can you take this?

**Comment by simon3z** [comment]
@moolitayer @zakiva can we close this?

**Comment by moolitayer** [comment]
Fixed by #15, closing.
@zakiva please see https://help.github.com/articles/closing-issues-using-keywords/
TLDR, write `fix #X` in a comment on your PR (preferably the first one to make your intentions clear)

**Comment by zakiva** [comment]
Yeah, thought "issue" was one of them :)

**Comment by moolitayer** [comment]
https://www.zoliblog.com/wp-content/uploads/2010/07/jira.jpg
