### ISSUE TITLE
Support metrics/alerts route detection on OCP v4

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-openshift#173]
Currently the "auto-detect" feature for hawkular/prometheus metrics and alerts only works on OCP v3.  On v4 the prometheus routes are in the openshift-monitoring namespace and hawkular isn't installed at all.

**Comment by chessbyte** [comment]
Part of Epic https://github.com/ManageIQ/manageiq-providers-openshift/issues/139
