### ISSUE TITLE
badge to the gitter room does not work

### ISSUE THREAD

**Issue by bsogithub** [ManageIQ/manageiq-providers-openshift#178]
When I click on the gitter join chat badge on https://github.com/ManageIQ/manageiq-providers-openshift readme, it gives me a 404 (https://gitter.im/ManageIQ/manageiq-providers-openshift?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by chessbyte** [comment]
Fixed
