### ISSUE TITLE
Add support for the OCP v4 alertmanager

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-providers-openshift#180]
OCP v3 had PrometheusAlertBuffer as the alerting system which is what ManageIQ supports.  OCP v4 uses a different system for cluster alerts which we should add support for.

https://prometheus.io/docs/alerting/alertmanager/

**Comment by chessbyte** [comment]
@agrare is this still an outstanding issue?

**Comment by agrare** [comment]
@chessbyte this is not implement yet

**Comment by Fryguy** [comment]
We should consider removing the alert UI interface entirely, which makes this not necessary.

**Comment by Fryguy** [comment]
Closing in favor of this being put on the chopping block and removing the UI in https://github.com/ManageIQ/manageiq-ui-classic/issues/8683
