### ISSUE TITLE
How do I actually run a scan?

### ISSUE THREAD

**Issue by booboothefool** [ManageIQ/manageiq-providers-openshift#187]
I was able to add my provider:

![image](https://user-images.githubusercontent.com/13257645/87822707-f230ca00-c83f-11ea-9b92-662c935c3bfc.png)

Although not sure what to put here:
![image](https://user-images.githubusercontent.com/13257645/87822738-0248a980-c840-11ea-9b7e-54ce1fb55f52.png)

I added OpenSCAP policy profile:
![image](https://user-images.githubusercontent.com/13257645/87822798-17bdd380-c840-11ea-9d8f-b31ff430c2f0.png)
![image](https://user-images.githubusercontent.com/13257645/87823129-c5c97d80-c840-11ea-93c2-40e884a398d1.png)

I also tried checking images and clicking "Check Compliance of Last Known Configuration".

Now I'm expecting everything to scan and show OpenSCAP results but I see no results/no last scan attempts:
![image](https://user-images.githubusercontent.com/13257645/87822955-6d927b80-c840-11ea-915c-2874a9658e8b.png)

![image](https://user-images.githubusercontent.com/13257645/87823036-96b30c00-c840-11ea-80cc-8b6e1f764878.png)

Am I missing a step?

**Comment by agrare** [comment]
@booboothefool you can run a container smartstate scan by going to a container image and clicking "Configuration / Perform SmartState Analysis"  The container provider then orchestrates deploying the image scan pod with the right permissions.  This isn't working on openshift v4 at the moment which might be what you're running into.

**Comment by booboothefool** [comment]
@agrare  Right, that "Configuration / Perform SmartState Analysis" button is grayed out for me and disabled. Yes, I am running OCP 4.3. If that is the case, and there's nothing I can do for now, please let me know when OCP4 is added. Thanks!
