### ISSUE TITLE
move openshift specific events and settings

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-openshift#3]
see the [amazon settings](https://github.com/ManageIQ/manageiq-providers-amazon/blob/master/config/settings.yml) for what can be moved

similar to moving the settings we can also move event names (see [amazon](https://github.com/ManageIQ/manageiq-providers-amazon/pull/163/files) for an example)

**Comment by simon3z** [comment]
@nimrodshn can you look into this? Thanks.

**Comment by cben** [comment]
these might help identifying events to move: 
- https://github.com/ManageIQ/manageiq-content/tree/master/content/automate/ManageIQ/System/Event/EmsEvent/Kubernetes.class
- https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/container_manager/event_catcher_mixin.rb

**Comment by nimrodshn** [comment]
made a PR for this: https://github.com/ManageIQ/manageiq-providers-openshift/pull/11.

**Comment by simon3z** [comment]
> made a PR for this: #11.

@nimrodshn WRT how to link issues and PRs check these:

https://help.github.com/articles/closing-issues-via-commit-messages
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by nimrodshn** [comment]
@simon3z Thanks! @cben just mentioned this to me - good to know!

**Comment by cben** [comment]
Oopsie, I think strictly speaking the events should have gone to kubernetes repo?

When you move other settings, let's evaluate where each one belongs...

**Comment by simon3z** [comment]
> Oopsie, I think strictly speaking the events should have gone to kubernetes repo?
> 
> When you move other settings, let's evaluate where each one belongs...

@nimrodshn @cben let's move it if it belongs there.

**Comment by simon3z** [comment]
@moolitayer can you check what's the status on this? Can we close it?

**Comment by moolitayer** [comment]
All the items here seem to be completed by:

- https://github.com/ManageIQ/manageiq-providers-openshift/pull/16
- https://github.com/ManageIQ/manageiq/pull/15178
- https://github.com/ManageIQ/manageiq-providers-openshift/pull/11

Closing, if more settings to move have been identified please open a new issue.
I can't locate any at this time.
