### ISSUE TITLE
bad request response when trying to add openshift provider via api

### ISSUE THREAD

**Issue by jmontleon** [ManageIQ/manageiq-providers-openshift#93]
{"error":{"kind":"bad_request","message":"Could not create the new provider - undefined method `api_allowed_attributes' for #\u003cClass:0x0055635da69800\u003e","klass":"Api::BadRequestError"}}

Adding   
```
def self.api_allowed_attributes
  return []
end
```
to container_manager.rb was enough to allow me to proceed.

This is getting called at: https://github.com/ManageIQ/manageiq-api/blob/ef464d1776f4f5c8e9bfc11c4c6da2f3981a76d1/app/controllers/api/providers_controller.rb#L199

**Comment by cben** [comment]
Thanks for detailed report :+1:.  I'm not managing to reproduce on master though.
It should have been inherited from ExtManagementSystem.api_allowed_attributes, added in https://github.com/ManageIQ/manageiq/pull/16802
Could it be you have old core manageiq with a new manageiq-api checkout?

**Comment by jmontleon** [comment]
It's possible. I'm using the pods at https://hub.docker.com/u/manageiq/

Perhaps somethings a little out of date. I'll do some digging and get back.

**Comment by jmontleon** [comment]
@cben it looks like the core manageiq installed on the images is out of date. That PR is missing. I think  https://hub.docker.com/r/manageiq/manageiq-ui-worker/ specifically was the one I had to update to get it to work.

It looks like that PR was merged on Feb 7 and manageiq/manageiq-ui-worker:latest is only 5 weeks old, but the CHANGELOG.md looks like it's from 2018-01-15 `## Unreleased as of Sprint 77 ending 2018-01-15'

Anyway, I'm guessing this is not the right place to request the image(s) to be updated. Is there somewhere I can do that?

Thanks!

**Comment by Ladas** [comment]
@simaishi any idea about the released images above ^

**Comment by simaishi** [comment]
We don't have automatic build set up for those worker images yet and I think @carbonin built manually and pushed them to Docker Hub last time. Will get those images updated.

**Comment by jmontleon** [comment]
Thank you @simaishi !

**Comment by simaishi** [comment]
@carbonin is taking the task to set up nightly, so passing on the "thank you" to him 😄

**Comment by carbonin** [comment]
I think it's best to use the released images so `gaprindashvili` and soon `hammer`.

These both have builds set up so they shouldn't have issues.

If you're still having problems, open up an issue on the manageiq-pods repo.
This can be closed.
